In [1]:
import pandas as pd

In [3]:
df_books =pd.read_csv('https://raw.githubusercontent.com/sanketchavan5595/EDA-on-bestselling-books-on-Amazon-/main/bestsellers%20with%20categories.csv')
df_books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [4]:
def two_times(values):
  return values*2

In [5]:
df_books['Rating_2']=df_books['User Rating'].apply(two_times) #aplica la funci√≥n a la columna establecida

In [6]:
df_books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6

In [7]:
df_books['Rating_2']=df_books['User Rating'].apply(lambda x:x*2) #sin√≥nimo con lambda

In [8]:
df_books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6

In [11]:
#aplica la funci√≥n a todo el DataFrame con una condici√≥n, se indica el axis 1 (columnas) para poder obtener los valores correctos
df_books['Rating_2']=df_books.apply(lambda x: x['User Rating']*2 if x['Genre']=='Fiction' else x['User Rating'],axis=1)
df_books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4.7
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,4.7
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4.8